# Promtail configuration for shipping logs to Loki

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # API logs
  - job_name: api
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          service: thoughtprocessor-api
          component: backend
          __path__: /var/log/api/*.log

  # Batch processor logs
  - job_name: batch-processor
    static_configs:
      - targets:
          - localhost
        labels:
          job: batch-processor
          service: kafka-worker
          component: worker
          __path__: /var/log/batch/*.log

  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
