# Prometheus configuration for Thought Processor monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'thoughtprocessor'
    environment: 'development'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # FastAPI application metrics
  - job_name: 'api'
    scrape_interval: 10s
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'api'
          component: 'backend'
    metrics_path: '/metrics'

  # Batch processor workers
  - job_name: 'kafka-workers'
    scrape_interval: 15s
    static_configs:
      - targets: ['kafka-worker:8001']
        labels:
          service: 'kafka-worker'
          component: 'batch-processor'
    metrics_path: '/metrics'

  # PostgreSQL database metrics
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgresql'
          component: 'database'

  # Redis cache metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          component: 'cache'

  # Kafka metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
        labels:
          service: 'kafka'
          component: 'message-queue'

  # System metrics (CPU, memory, disk, network)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'
          component: 'system'
